apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-config-production
  labels:
    app: cp-config-production
    env: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cp-config-production
      env: production
  template:
    metadata:
      name: cp-config-production
      labels:
        app: cp-config
        env: production
    spec:
      containers:
        - name: cp-config-production
          image: baguette6/cp-config:latest
          imagePullPolicy: Always
          readinessProbe:
            periodSeconds: 60
            httpGet:
              path: /healthz/ready
              port: 80
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://*:80"
            - name: SECRETS_MANAGER_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-access-token
                  key: secrets-manager-access-token
      restartPolicy: Always