ConfigSuppliersCount: 2
StaticStages:
  - "main"
  - "development"
Environments:
  - "development"
  - "staging"
  - "production"
Git:
  Repository: "https://github.com/simpleg-eu/cp-config-files.git"
  UsernameSecret: "89550bb0-6d76-467c-92c8-b0c601080978"
  PasswordSecret: "2d4c986f-3064-44a1-a4c3-b0c60108308c"
TcpListener:
  Address: "0.0.0.0"
  Port: "3000"
Timeouts:
  ControllersConfigGetConfig: 15
Authorization:
  Issuers:
    - "https://simpleg.eu.auth0.com/"
  Audience:
    - "cp-config"
  JwksUri: "https://simpleg.eu.auth0.com/.well-known/jwks.json"