apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cuplan-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite /cp-config/(.*) /$1 break;
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* /healthz(/|$) {
        deny all;
        return 403;
      }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - s1.simpleg.eu
      secretName: s1-simpleg-tls
  rules:
    - host: s1.simpleg.eu
      http:
        paths:
          - path: /cp-config
            pathType: Prefix
            backend:
              service:
                name: cp-config-service
                port:
                  number: 3000