apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cuplan-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite /cp-config/production/(.*) /$1 break;
      rewrite /cp-config/staging/(.*) /$1 break;
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* /cp-config/healthz(/|$) {
        deny all;
        return 403;
      }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - host.simpleg.eu
      secretName: host-simpleg-tls
  rules:
    - host: host.simpleg.eu
      http:
        paths:
          - path: /cp-config/production
            pathType: Prefix
            backend:
              service:
                name: cp-config-production-service
                port:
                  number: 1080
          - path: /cp-config/staging
            pathType: Prefix
            backend:
              service:
                name: cp-config-staging-service
                port:
                  number: 2080
                