apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-config
  labels:
    app: cp-config
    env: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cp-config
      env: production
  template:
    metadata:
      name: cp-config
      labels:
        app: cp-config
        env: production
    spec:
      containers:
        - name: cp-config
          image: gabriel0simpleg/cp-config:latest
          imagePullPolicy: Always
          readinessProbe:
            periodSeconds: 60
            httpGet:
              path: /healthz/ready
              port: 3000
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 3000
          env:
            - name: SECRETS_MANAGER_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-access-token
                  key: secrets-manager-access-token
          volumeMounts:
            - name: cp-config-development-configuration
              mountPath: /cp-config/config
      restartPolicy: Always
      volumes:
        - name: cp-config-configuration
          hostPath:
            path: {PATH} # custom path to the config directory 