apiVersion: v1
kind: Service
metadata:
  name: cp-config-service
spec:
  selector:
    app: cp-config
    env: production
  ports:
    - protocol: TCP
      port: 1080
      targetPort: 80
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cp-config-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - host.simpleg.eu
      secretName: cp-config-tls
  rules:
    - host: host.simpleg.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cp-config-service
                port:
                  number: 1080