apiVersion: v1
kind: Service
metadata:
  name: cp-config-service
spec:
  selector:
    app: cp-config
    env: production
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3000
  type: LoadBalancer