apiVersion: v1
kind: Service
metadata:
  name: cp-config-development-service
spec:
  selector:
    app: cp-config-development
    env: development
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3000
  type: LoadBalancer