apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-config-development
  labels:
    app: cp-config-development
    env: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cp-config-development
      env: development
  template:
    metadata:
      name: cp-config-development
      labels:
        app: cp-config-development
        env: development
    spec:
      containers:
        - name: cp-config-development
          image: gabriel0simpleg/cp-config:latest
          imagePullPolicy: Always
          readinessProbe:
            periodSeconds: 60
            httpGet:
              path: /healthz/ready
              port: 3000
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 3000
          env:
            - name: SECRETS_MANAGER_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secrets-manager-access-token
                  key: secrets-manager-access-token
          volumeMounts:
            - name: cp-config-development-configuration
              mountPath: /cp-config/config
      restartPolicy: Always
      volumes:
        - name: cp-config-development-configuration
          hostPath:
            path: "$CP_CONFIG_CONFIG_PATH"